CREATE DATABASE IF NOT EXISTS sensores_db;
USE sensores_db;

CREATE TABLE IF NOT EXISTS clima (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_nodo VARCHAR(50),
  temperatura FLOAT,
  humedad FLOAT,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gases (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_nodo VARCHAR(50),
  co2 FLOAT,
  volatiles FLOAT,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
